# Generated by Django 2.0.3 on 2018-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Study')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'verbose_name': 'Study',
            },
        ),
    ]
