# Generated by Django 2.0.3 on 2018-04-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam_date',
            new_name='exam',
        ),
    ]
