# Generated by Django 2.0.3 on 2018-04-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_exam_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinformation',
            old_name='examdate',
            new_name='exam',
        ),
    ]
