# Generated by Django 2.0.4 on 2018-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        ('exams', '0003_rename_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='study',
        ),
        migrations.AddField(
            model_name='lecture',
            name='studies',
            field=models.ManyToManyField(related_name='lectures', to='studies.Study'),
        ),
    ]
