# Generated by Django 2.0.4 on 2018-04-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_link_lecture_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.Lecture'),
        ),
    ]
